ekyna_characteristics_choice_admin_home:
    path: /home
    defaults: { _controller: "EkynaCharacteristicsBundle:Choices:home" }
    methods: [GET]

ekyna_characteristics_choice_admin_list:
    path: /{name}/list
    defaults: { _controller: "EkynaCharacteristicsBundle:Choices:list" }
    methods: [GET]

ekyna_characteristics_choice_admin_new:
    path: /{name}/new
    defaults: { _controller: "EkynaCharacteristicsBundle:Choices:new" }
    methods: [GET|POST]

ekyna_characteristics_choice_admin_show:
    path: /{name}/{choiceId}/show
    defaults: { _controller: "EkynaCharacteristicsBundle:Choices:show" }
    methods: [GET]

ekyna_characteristics_choice_admin_edit:
    path: /{name}/{choiceId}/edit
    defaults: { _controller: "EkynaCharacteristicsBundle:Choices:edit" }
    methods: [GET|POST]

ekyna_characteristics_choice_admin_remove:
    path: /{name}/{choiceId}/remove
    defaults: { _controller: "EkynaCharacteristicsBundle:Choices:remove" }
    methods: [GET|POST]
